[package]
name = "pinenotectl"
version = "0.1.0"
edition = "2021"
description = "Control the PineNote's special features"
license = "MIT"
repository = "https://github.com/jzbor/pinenotectl"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
colored = "3.0.0"
zbus = "5.5.0"
