//! # D-Bus interface proxy for: `org.pinenote.misc`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `pn-misc-inspection.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.pinenote.misc", default_path = "/misc", default_service = "org.pinenote.misc")]
pub trait Misc {
    /// DisableTravelMode method
    fn disable_travel_mode(&self) -> zbus::Result<()>;

    /// EnableTravelMode method
    fn enable_travel_mode(&self) -> zbus::Result<()>;

    /// GetTravelMode method
    fn get_travel_mode(&self) -> zbus::Result<u32>;

    /// TravelModeChanged signal
    #[zbus(signal)]
    fn travel_mode_changed(&self) -> zbus::Result<()>;
}
